<?php

namespace Database\Seeders;

use App\Models\Agenda;
use Illuminate\Database\Seeder;

class AgendaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Agenda::insert([
            [
                'nome' => 'mattina',
                'user_id' => 9,
                'settimana' => 2,
                'lun' => null,
                'mar' => null,
                'mer' => 'Blu Gallery',
                'gio' => null,
                'ven' => null,
            ],
            [
                'nome' => 'pomeriggio',
                'user_id' => 9,
                'settimana' => 2,
                'lun' => null,
                'mar' => null,
                'mer' => 'Blu Gallery',
                'gio' => null,
                'ven' => null,
            ],
            [
                'nome' => 'mattina',
                'user_id' => 9,
                'settimana' => 4,
                'lun' => null,
                'mar' => null,
                'mer' => 'Blu Gallery',
                'gio' => null,
                'ven' => null,
            ],
            [
                'nome' => 'pomeriggio',
                'user_id' => 9,
                'settimana' => 4,
                'lun' => null,
                'mar' => null,
                'mer' => 'Blu Gallery',
                'gio' => null,
                'ven' => null,
            ],
            [
                'nome' => 'mattina',
                'user_id' => 5,
                'settimana' => 1,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Pisa',
                'gio' => 'Pisa',
                'ven' => 'Pisa',
            ],
            [
                'nome' => 'pomeriggio',
                'user_id' => 5,
                'settimana' => 1,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Livorno',
                'gio' => 'Lammari',
                'ven' => 'Livorno',
            ],
            [
                'nome' => 'mattina',
                'user_id' => 5,
                'settimana' => 2,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Pisa',
                'gio' => 'Pisa',
                'ven' => 'Pisa',
            ],
            [
                'nome' => 'pomeriggio',
                'user_id' => 5,
                'settimana' => 2,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Livorno',
                'gio' => 'Lammari',
                'ven' => 'Livorno',
            ],

            [
                'nome' => 'mattina',
                'user_id' => 5,
                'settimana' => 3,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Pisa',
                'gio' => 'Pisa',
                'ven' => 'Pisa',
            ],
            [
                'nome' => 'pomeriggio',
                'user_id' => 5,
                'settimana' => 3,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Livorno',
                'gio' => 'Lammari',
                'ven' => 'Livorno',
            ],

            [
                'nome' => 'mattina',
                'user_id' => 5,
                'settimana' => 4,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Pisa',
                'gio' => 'Pisa',
                'ven' => 'Pisa',
            ],
            [
                'nome' => 'pomeriggio',
                'user_id' => 5,
                'settimana' => 4,
                'lun' => 'Pisa',
                'mar' => 'Pisa',
                'mer' => 'Livorno',
                'gio' => 'Lammari',
                'ven' => 'Livorno',
            ],
            /*           [
                           'nome' => 'mattina',
                           'user_id' => 5,
                           'settimana' => 3,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'pomeriggio',
                           'user_id' => 5,
                           'settimana' => 3,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'mattina',
                           'user_id' => 5,
                           'settimana' => 4,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'pomeriggio',
                           'user_id' => 5,
                           'settimana' => 4,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],

                       [
                           'nome' => 'mattina',
                           'user_id' => 2,
                           'settimana' => 1,
                           'lun' => 'Filiale',
                           'mar' => 'OTTICA BLU',
                           'mer' => 'Filiale',
                           'gio' => 'DOTT. ZAMPI',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'pomeriggio',
                           'user_id' => 2,
                           'settimana' => 1,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'mattina',
                           'user_id' => 2,
                           'settimana' => 2,
                           'lun' => 'Filiale',
                           'mar' => 'FARMACIA ROSSI',
                           'mer' => 'Filiale',
                           'gio' => 'DOTT. NERI',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'pomeriggio',
                           'user_id' => 2,
                           'settimana' => 2,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'mattina',
                           'user_id' => 2,
                           'settimana' => 3,
                           'lun' => 'Filiale',
                           'mar' => 'STUDIO VERDI',
                           'mer' => 'Filiale',
                           'gio' => 'FARMACIA COM.1',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'pomeriggio',
                           'user_id' => 2,
                           'settimana' => 3,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'mattina',
                           'user_id' => 2,
                           'settimana' => 4,
                           'lun' => 'Filiale',
                           'mar' => 'FARMACIA BIANCHI',
                           'mer' => 'Filiale',
                           'gio' => 'FARMACIA COM.2',
                           'ven' => 'Filiale',
                       ],
                       [
                           'nome' => 'pomeriggio',
                           'user_id' => 2,
                           'settimana' => 4,
                           'lun' => 'Filiale',
                           'mar' => 'Filiale',
                           'mer' => 'Filiale',
                           'gio' => 'Filiale',
                           'ven' => 'Filiale',
                       ],*/
        ]);
    }
}
