<?php

namespace Database\Seeders;

use App\Models\Budget;
use Illuminate\Database\Seeder;

class BudgetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Budget::insert([
            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 2,
                'budgetAnno' => 200000,
                'stipendio' => 3000,
                'provvigione' => 10,
                'gennaio' => 12000,
                'febbraio' => 16000,
                'marzo' => 20000,
                'aprile' => 20000,
                'maggio' => 20000,
                'giugno' => 20000,
                'luglio' => 12000,
                'agosto' => 12000,
                'settembre' => 16000,
                'ottobre' => 20000,
                'novembre' => 20000,
                'dicembre' => 12000,
            ],
            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 3,
                'budgetAnno' => 150000,
                'stipendio' => 3000,
                'provvigione' => 10,
                'gennaio' => 9000,
                'febbraio' => 12000,
                'marzo' => 15000,
                'aprile' => 15000,
                'maggio' => 15000,
                'giugno' => 15000,
                'luglio' => 9000,
                'agosto' => 9000,
                'settembre' => 12000,
                'ottobre' => 15000,
                'novembre' => 15000,
                'dicembre' => 9000,
            ],

            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 5,
                'budgetAnno' => 80000,
                'stipendio' => 3000,
                'provvigione' => 8,
                'gennaio' => 4800,
                'febbraio' => 6400,
                'marzo' => 8000,
                'aprile' => 8000,
                'maggio' => 8000,
                'giugno' => 8000,
                'luglio' => 4800,
                'agosto' => 4800,
                'settembre' => 6400,
                'ottobre' => 8000,
                'novembre' => 8000,
                'dicembre' => 4800,
            ],
            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 6,
                'budgetAnno' => 100000,
                'stipendio' => 1500,
                'provvigione' => 20,
                'gennaio' => 6000,
                'febbraio' => 8000,
                'marzo' => 10000,
                'aprile' => 10000,
                'maggio' => 10000,
                'giugno' => 10000,
                'luglio' => 6000,
                'agosto' => 6000,
                'settembre' => 8000,
                'ottobre' => 10000,
                'novembre' => 10000,
                'dicembre' => 6000,
            ],
            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 9,
                'budgetAnno' => 150000,
                'stipendio' => 1500,
                'provvigione' => 20,
                'gennaio' => 9000,
                'febbraio' => 12000,
                'marzo' => 15000,
                'aprile' => 15000,
                'maggio' => 15000,
                'giugno' => 15000,
                'luglio' => 9000,
                'agosto' => 9000,
                'settembre' => 12000,
                'ottobre' => 15000,
                'novembre' => 15000,
                'dicembre' => 9000,
            ],
            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 8,
                'budgetAnno' => 80000,
                'stipendio' => 3000,
                'provvigione' => 8,
                'gennaio' => 4800,
                'febbraio' => 6400,
                'marzo' => 8000,
                'aprile' => 8000,
                'maggio' => 8000,
                'giugno' => 8000,
                'luglio' => 4800,
                'agosto' => 4800,
                'settembre' => 6400,
                'ottobre' => 8000,
                'novembre' => 8000,
                'dicembre' => 4800,
            ],
            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 4,
                'budgetAnno' => 20000,
                'stipendio' => null,
                'provvigione' => null,
                'gennaio' => 1200,
                'febbraio' => 1600,
                'marzo' => 2000,
                'aprile' => 2000,
                'maggio' => 2000,
                'giugno' => 2000,
                'luglio' => 1200,
                'agosto' => 1200,
                'settembre' => 1600,
                'ottobre' => 2000,
                'novembre' => 2000,
                'dicembre' => 1200,
            ],
            [
                'nome' => 'Budget',
                'anno' => 2022,
                'user_id' => 12,
                'budgetAnno' => 150000,
                'stipendio' => 3000,
                'provvigione' => 10,
                'gennaio' => 9000,
                'febbraio' => 12000,
                'marzo' => 15000,
                'aprile' => 15000,
                'maggio' => 15000,
                'giugno' => 15000,
                'luglio' => 9000,
                'agosto' => 9000,
                'settembre' => 12000,
                'ottobre' => 15000,
                'novembre' => 15000,
                'dicembre' => 9000,
            ],
        ]);
    }
}
