const help = () => {
    return {

/*        linklogin: 'http://localhost/api/login',
        linklogout: 'http://localhost/api/logout',
        linkfiliali: 'http://localhost/api/filiali',
        linkcanali: 'http://localhost/api/canali',
        linkaddcanale: 'http://localhost/api/addCanale',*/

        linklogin: 'http://vuexdocker.test/api/login',
        linklogout: 'http://vuexdocker.test/api/logout',
        linkcanali: 'http://vuexdocker.test/api/canali',
        linkaddcanale: 'http://vuexdocker.test/api/addCanale',
        linkfornitori: 'http://vuexdocker.test/api/fornitori',
        linkaddfornitore: 'http://vuexdocker.test/api/addFornitore',
        linklistino: 'http://vuexdocker.test/api/listino',
        linkelelistino: 'http://vuexdocker.test/api/eleListino',
        linkaddlistino: 'http://vuexdocker.test/api/addListino',
        linkcategorie: 'http://vuexdocker.test/api/categorie',
        linkaddcategoria: 'http://vuexdocker.test/api/addCategoria',
        linkruoli: 'http://vuexdocker.test/api/ruoli',
        linkaddruolo: 'http://vuexdocker.test/api/addRuolo',
        linkaudio: 'http://vuexdocker.test/api/audio',
        linkaudioconbgt: 'http://vuexdocker.test/api/audioConBgt',
        linkaudiosenzabgt: 'http://vuexdocker.test/api/audioSenzaBgt',
        linkamm: 'http://vuexdocker.test/api/amm',
        linkuser: 'http://vuexdocker.test/api/user',
        linkadduser: 'http://vuexdocker.test/api/addUser',
        linkfiliali: 'http://vuexdocker.test/api/filiali',
        linkaddfiliale: 'http://vuexdocker.test/api/addFiliale',
        linkrecapiti: 'http://vuexdocker.test/api/recapiti',
        linkrecapitiperaudio: 'http://vuexdocker.test/api/recapitiPerAudio',
        linkaddrecapito: 'http://vuexdocker.test/api/addRecapito',
        linkrichiestaprodotti: 'http://vuexdocker.test/api/richiestaProdotti',
        linkclients: 'http://vuexdocker.test/api/clients',
        linkclientsfiliale: 'http://vuexdocker.test/api/clientsFiliale',
        linkaddclient: 'http://vuexdocker.test/api/addClient',
        linkmodificaclient: 'http://vuexdocker.test/api/modificaClient',
        linktipologie: 'http://vuexdocker.test/api/tipologie',
        linkaddtipologia: 'http://vuexdocker.test/api/addTipologia',
        linkmodificatipologia: 'http://vuexdocker.test/api/modificaTipologia',
        linkassociazioniPersonale: 'http://vuexdocker.test/api/associazioniPersonale',
        linkaggiungiAssociazione: 'http://vuexdocker.test/api/addAssocia',
        linkeliminaAssociazione: 'http://vuexdocker.test/api/eliminaAssocia',
        linkassegnabgt: 'http://vuexdocker.test/api/assegnaBgt',
        linkmodificabgt: 'http://vuexdocker.test/api/modificaBgt',
        linkaudiometrie: 'http://vuexdocker.test/api/listaAudiometrie',
        linkaudiometria: 'http://vuexdocker.test/api/audiometria',
        linkaddaudiometria: 'http://vuexdocker.test/api/addAudiometria',
        linkfilialefornitore: 'http://vuexdocker.test/api/filialeFornitore',
        linknuovaprova: 'http://vuexdocker.test/api/nuovaProva',
        linksalvaprova: 'http://vuexdocker.test/api/salvaProva',
        linkaddeleinprova: 'http://vuexdocker.test/api/addEleInProva',
        linkeliminaeleinprova: 'http://vuexdocker.test/api/provaProdotto',
        linkproductswitchinprova: 'http://vuexdocker.test/api/productSwitchInProva',
        linkproductswitchrimuovidallaprova: 'http://vuexdocker.test/api/productSwitchRimuoviDallaProva',
        linkresoprova: 'http://vuexdocker.test/api/resoProva',
        linksalvafattura: 'http://vuexdocker.test/api/salvaFattura',
        linkgetuser: 'http://vuexdocker.test/api/user',
        linksituazionemese: 'http://vuexdocker.test/api/situazioneMese',
        linkfilialiuser: 'http://vuexdocker.test/api/filialiUser',
        linkproductrimuovirichiesta: 'http://vuexdocker.test/api/productRimuoviRichiesta',
        linkappuntamenti: 'http://vuexdocker.test/api/appuntamentiCliente',
        linkaddappuntamento: 'http://vuexdocker.test/api/addAppuntamento',
        linkcompleanni: 'http://vuexdocker.test/api/compleanni',
        linkappuntamentioggi: 'http://vuexdocker.test/api/appuntamentiOggiAudio',
        linkvisualizzasituazioneanno: 'http://vuexdocker.test/api/visualizzaSituazioneAnno',
        linkinviasms: 'http://vuexdocker.test/api/inviaSms',
        linklistarichiestaapparecchi: 'http://vuexdocker.test/api/listaProdottiRichiesti',
        linkassegnaprodottimagazzino: 'http://vuexdocker.test/api/assegnaProdottiMagazzino',
        linkimmatricolati: 'http://vuexdocker.test/api/prodottiImmatricolati',
        linkswitchimmatricolato: 'http://vuexdocker.test/api/productSwitchImmatricolato',
        linkswitcharrivato: 'http://vuexdocker.test/api/productSwitchArrivato',
        linkuseragenda: 'http://vuexdocker.test/api/userAgenda',
    };
};
export default help;
